port: 37087
static_path: "/static"
proxy_settings:
  
  max_load: 5
  startup_servers: 3
  upscale_pings: 5
  downscale_pings : 30
  interval : 1

server_options:
  server1:
    prefix: /api
    command: venv/bin/uvicorn
    args: ["server:app","--uds","<sock>"]
    startup_servers: 1
    max_servers: 4
  server2:
    prefix: /admi
    command: venv/bin/uvicorn
    args: ["server:app","--uds","<sock>"]
    startup_servers: 1
    max_servers: 4
  