proxy_port: 8000
admin_port: 9000
static_path: "/static"
dynos: 
  scaler: true
  monitor: true
  
scaling_settings:
  max_load: 50
  min_load: 50
  upscale_pings: 5
  downscale_pings : 30
  interval : 1

server_options:
  server2:
    prefix: /api
    command: venv/bin/uvicorn
    args: ["server:app","--uds","<sock>"]
    startup_servers: 1
    max_servers: 4
  server1:
    prefix: /admin
    command: venv/bin/uvicorn
    args: ["server:app","--uds","<sock>"]
    startup_servers: 1
    max_servers: 4
  